#Travis CI (https://travis-ci.com)
language: java
install: true
script:
  - ./gradlew clean install check
#FIXME check style warns:
#  - mvn clean install checkstyle:check
  - mvn clean install 
jdk:
  - oraclejdk8
# https://travis-ci.org does not support it yet :/
#  - openjdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/97828e17fd4adcb37306
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
